### ISSUE TITLE
some bugs after last commits?

### ISSUE THREAD

**Issue by moebiussurfing** [Daandelange/ofxImGui#10]
hey @Daandelange ,
I noticed some problems on restoring the windows positions after some commits ago.
ie: All my windows are opening on the same place.

I am tryinng to reproduce on the add-on examples but I am not seeing it always... sorry. 
Also sometimes it seems that the positions after restarting are not exactly the same (?).

This has any sense or I did changed some other thing?

EDIT:
hmm it seems that also I still having some empty ofxImGui::Settings(); that overwrite the positions...

EDIT2:
that's bc I was ignoring the settings on my branch. I used to use empty setting just to fill the ofxImGui::BeginWindow args...
```.c++
Restore original ImGui behaviour affected by moebius' changes. (kept … 
@@ -98,9 +99,9 @@ bool ofxImGui::BeginWindow(const std::string& name, Settings& settings, ImGuiWin
	//ImGui::SetNextWindowPos(settings.windowPos, settings.lockPosition? ImGuiCond_Always : ImGuiCond_Appearing);
	//ImGui::SetNextWindowSize(settings.windowSize, ImGuiCond_Appearing);
	//ImGui::SetNextWindowCollapsed(!(flags & ImGuiWindowFlags_NoCollapse), ImGuiCond_Appearing);
	ImGui::SetNextWindowPos(settings.windowPos, settings.lockPosition? ImGuiCond_Always : ImGuiCond_Appearing);
	ImGui::SetNextWindowSize(settings.windowSize, ImGuiCond_Appearing);
	ImGui::SetNextWindowCollapsed(!(flags & ImGuiWindowFlags_NoCollapse), ImGuiCond_Appearing);
```
I am not sure but maybe, when you use the ofxImGui::BeginWindow/settings approach (required to feed ofParams), you lost the ImGui store layout/recall features...
That's what I do now: (btw, then I need to use my own ofParams helpers)
```.c++
_flagw = ImGuiWindowFlags_None;
_name = "RawWidgets";
ImGui::Begin(_name.c_str(), NULL, _flagw);
//if (ofxImGui::BeginWindow(_name.c_str(), mainSettings, _flagw))
{
  drawRawImGuiWidgets();
}
//ofxImGui::EndWindow(mainSettings);
ImGui::End();
```

Just clarifying myself. I close the issue.

--

Also, on the example-demo I am getting this error on main.cpp:
```
#else
    ofGLESWindowSettings settings;
    settings.setGLVersion(3,2); <------------- error: setGLVersion not exist
#endif
    settings.setSize..
```

In example-simple (ofApp.h): I had to comment //#include "glfw3.h"

**Comment by Daandelange** [comment]
Hey Manu,
`#include "glfw3.h"` and `setGLVersion()` are already on their way in a next commit, thanks for the notices.

> All my windows are opening on the same place.

Ain't that normal behaviour ? Using raw `ImGui::Begin()`, I think it is normal, but maybe not using the helpers ?
I just tested it in the original repo, the Helpers do not seem to have some auto-layout feature. (it could be in the future!?)

Anyways, you're right that the window restore feature is broken after my restore commit.
In fact, it just occurred to me that the solution might be very simple : `ImGuiCond_Appearing` should be `ImGuiCond_FirstUseEver` now that we use window restoring. And also, `ImGuiWindowFlags_NoSavedSettings` is interfearing with the recall feature. I think Jason set that to disable ini recalling, but now it's done via `ImGui::GetIO()` in `gui.setup()`, so I'm gonna remove that flag too.

> ofxImGui::Settings(); that overwrite the positions

It's really not clear to me what `settings.windowPos` and `settings.windowSize` are used for. What I understand:
1. Set window position, only when appearing or with `settings.lockedPosition`.
2. Query window position after it's been drawn.

So it seems more like a getter then a setter, but a little of both.

If you wanna try, here' what I'll push soon :
````cpp
bool ofxImGui::BeginWindow(const std::string& name, Settings& settings, ImGuiWindowFlags flags, bool * open)
{
	// [...]  Stripped code ...
        
	ImGui::SetNextWindowPos(settings.windowPos, settings.lockPosition? ImGuiCond_Always : ImGuiCond_FirstUseEver);
	ImGui::SetNextWindowSize(settings.windowSize, ImGuiCond_FirstUseEver);
	if(!(flags & ImGuiWindowFlags_NoCollapse)) ImGui::SetNextWindowCollapsed(true, ImGuiCond_Appearing); // Initially collapse collapsible windows
	return ImGui::Begin(name.c_str(), open, flags);
}
````

Does that answer your questions ? Fix your issues ?

**Comment by moebiussurfing** [comment]
Ok. Thanks. Yes this settings thing is a bit mess.

Maybe you can add a more raw/simple method using the current ones. I mean something like simplify this:
`bool ofxImGui::BeginWindow(const std::string& name, Settings& settings, ImGuiWindowFlags flags, bool * open)`
to
`bool ofxImGui::BeginWindow(const std::string& name, bool * open,  ImGuiWindowFlags flags)`
exact the same args than: ImGui::Begin(

Then if for some reason settings must be there (to monitor window states, queued names, mouse over etc), you can put it inside the above method too "just to be there". (but hidding it from the args or the user).

--

These times I am not using ofxImGui helpers anymore. Bc I don't like to use the settings stuff to handle the windows layout (pos/size). Also I prefer to stay raw/ImGui + ofParms.

I am using raw ImGui::Begin instead of ofxImGui::BeginWindow.

On [my add-on](https://github.com/moebiussurfing/ofxSurfingImGui) I have my own oF params helpers. 
I am still having problems bc I need to add some uniqueNames workaround; I'll fix this someday.
(or maybe I'll go back or will restore some of the ofxImGui helpers stuff.. Never ending story hehe.)
