### ISSUE TITLE
compiling error w of_0.12

### ISSUE THREAD

**Issue by cyberboy666** [Daandelange/ofxImGui#21]
might be missing something (dont know too much about cpp etc) but when i clone this repo and try compile `example-simple` in of_v0.11.2 it works fine, however when i try the same in of_v0.12 i get this error:

```
ofxImGui/src/LinkedList.hpp:59:43: error: expected unqualified-id before ‘const’
   59 |                 LinkedList<T_KEY,T_DATA>( const LinkedList<T_KEY,T_DATA>& ) = delete;
      |                                           ^~~~~

```

im running pop_os btw, following ubuntu install guide...

**Comment by Daandelange** [comment]
Hi, thanks for your report. It seems identical to https://github.com/jvcleave/ofxImGui/issues/120, let's continue there !
