### ISSUE TITLE
Apple Mach-0 Linker (id) error

### ISSUE THREAD

**Issue by RomainAl** [Daandelange/ofxImGui#4]
Hi ! Thx for all your works ! But when I'm trying to build the "example-demo" I have this error that I don't understand ! Could you help me ? I'm from Processing / Matlab, so I'm pretty noob in C++/Xcode coding... sorry !
Thanks in advance !
<img width="1512" alt="Capture d’écran 2021-01-24 à 17 42 49" src="https://user-images.githubusercontent.com/60849348/105637120-0b0fdd00-5e6c-11eb-94a5-45eff65fedc0.png">

**Comment by Daandelange** [comment]
Hey, I've just tested with XCode and it seems to compile fine here. I guess you're using the JVCleave branch ? It looks like you're trying to bring a custom theme in the demo window. Maybe you need to regenerate your project with the PG so it finds the new theme files that you added ? Maybe your custom theme file got some conflicts ?

**Comment by RomainAl** [comment]
Yes, there was a conflit with my custom theme ! Thx for your answer !
