### ISSUE TITLE
AddGroup crashes because of missing if statement

### ISSUE THREAD

**Issue by thomasgeissl** [Daandelange/ofxImGui#5]
Hey Dan,
there is a bug in jvcleave branch. The following snippet should be added, otherwise it will crash trying to add a nullptr

```
            if(parameterColor)
```

https://github.com/Daandelange/ofxImGui/blob/jvcleave/src/ImHelpers.cpp#L240

**Comment by Daandelange** [comment]
Hey Thomas, thanks for the report, I'll change that.

**Comment by moebiussurfing** [comment]
hey, thanks @thomasgeissl ,
sorry @Daandelange, I have not received any notification. I just updated the watch-all tick

**Comment by Daandelange** [comment]
Np, I had the same issue, I didn't get any notification for Thomas' issues.
