### ISSUE TITLE
New plugin name ?

### ISSUE THREAD

**Issue by Daandelange** [Daandelange/ofxImGui#8]
Thinking about `ofxDearImGui`.
Any ideas ? @moebiussurfing @d3cod3

**Comment by d3cod3** [comment]
Cool one! i like it

**Comment by moebiussurfing** [comment]
yes, is cute.

**Comment by thomasgeissl** [comment]
not sure how much it diverged already from the original addon, but I would love to see that being merged back. 
If it is for whatever reason not possible, ofxDearImGui is great.

**Comment by Daandelange** [comment]
Me too, but no response from @jvcleave until now. I'll try to drop him a mail. _Edit: Got a response._

In short :  
There are (slightly) breaking API changes and lots of new stuff, mostly adapting the plugin to imgui's new features, some new helper functions (fonts, ...).  
More problematically, Vulkan [`imgui_impl_vulkan`] and iOS [`imgui_impl_osx`] support is dropped (unless someone ports and tests a backend for it), maybe some rpi support drops too, as there seem to be many ways to setup oF on Rpis. In fact only oF with GLFW windows are implemented, specially if the "legacy backend" is stripped (see #7). SDL windows could be implemented too [for which some experimental work has already been done, I think].

On the other side, this fork is the natural evolution of ofxImGui in the sense of keeping imgui updated. Jvcleave/ofxImGui is now stuck at imgui 1.79 max, forever.
